### ISSUE TITLE
worker reference is above timeclock in tree

### ISSUE THREAD

**Issue by andhess** [Staffjoy/client_python#1]
https://github.com/StaffJoy/client_python/blob/master/staffjoy/resources/worker.py

needs to have functions to access timeclocks

**Comment by andhess** [comment]
https://github.com/StaffJoy/client_python/blob/master/staffjoy/resources/timeclock.py

timeclocks are nested underneath user

**Comment by philipithomas** [comment]
``` python

# timeclocks.py
apiv1_rest.add_resource(TimeclocksApi,
        "/organizations/<int:org_id>/locations/<int:location_id>/roles/<int:role_id>/users/<int:user_id>/timeclocks/")

# timeclock.py
apiv1_rest.add_resource(TimeclockApi,
        "/organizations/<int:org_id>/locations/<int:location_id>/roles/<int:role_id>/users/<int:user_id>/timeclocks/<int:timeclock_id>")

#
```

**Comment by andhess** [comment]
and remove timeclock from role resource 

https://github.com/StaffJoy/client_python/blob/master/staffjoy/resources/role.py
